global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        username: 'Kafka Monitor'
        channel: '#test'
        api_url: 'https://hooks.slack.com/services/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'
